### ISSUE TITLE
Uncaught Error: Class 'DUP_Logs' not found

### ISSUE THREAD

**Issue by Alpine418** [flydev-fr/Duplicator#22] opened 2022-03-23 14:45 UTC
When I've "FTP upload" enabled then I'am getting the following error:

`[23-Mar-2022 15:44:01 Europe/Zurich] PHP Fatal error:  Uncaught Error: Class 'DUP_Logs' not found in C:\foo\bar\site\modules\Duplicator\Classes\FTPClient.php:58
Stack trace:
#0 C:\foo\bar\site\modules\Duplicator\Duplicator.module(641): FTPClient->connect()
#1 C:\foo\bar\wire\core\Wire.php(417): ProcessWire\Duplicator->___cronJob(Object(ProcessWire\HookEvent))
#2 C:\foo\bar\wire\core\WireHooks.php(951): ProcessWire\Wire->_callMethod('___cronJob', Array)
#3 C:\foo\bar\wire\core\Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Duplicator), 'cronJob', Array)
#4 C:\foo\bar\site\modules\Duplicator\Duplicator.module(289): ProcessWire\Wire->__call('cronJob', Array)
#5 C:\foo\bar\wire\core\Modules.php(682): ProcessWire\Duplicator->init()
#6 C:\foo\bar\wire\core\Modules.php(1448): ProcessWire\Modules->initModule(Object(ProcessWire\Duplicator), Array)
#7 C:\dev\Wampserver\www\f2ps.loc in C:\foo\bar\site\modules\Duplicator\Classes\FTPClient.php on line 58
[23-Mar-2022 15:44:01 Europe/Zurich] PHP Warning:  Cannot modify header information - headers already sent in C:\foo\bar\wire\core\WireHttp.php on line 1649
[23-Mar-2022 15:44:01 Europe/Zurich] PHP Stack trace:
[23-Mar-2022 15:44:01 Europe/Zurich] PHP   1. ProcessWire\WireShutdown->shutdown() C:\foo\bar\wire\core\WireShutdown.php:0
[23-Mar-2022 15:44:01 Europe/Zurich] PHP   2. ProcessWire\WireShutdown->sendFatalHeader() C:\foo\bar\wire\core\WireShutdown.php:581
[23-Mar-2022 15:44:01 Europe/Zurich] PHP   3. ProcessWire\WireHttp->sendStatusHeader() C:\foo\bar\wire\core\WireShutdown.php:405
[23-Mar-2022 15:44:01 Europe/Zurich] PHP   4. ProcessWire\WireHttp->sendHeader() C:\foo\bar\wire\core\WireHttp.php:1671
[23-Mar-2022 15:44:01 Europe/Zurich] PHP   5. header() C:\foo\bar\wire\core\WireHttp.php:1649
`

**Comment by rjgamer** [comment] 2022-03-23 14:46
Looks like the issue is maybe the missing namespace "ProcessWire" in the "FTP client" class.

**Comment by Alpine418** [comment] 2022-03-23 14:50
The problem is the missing ProcessWire namespace in the FtpClient Class. 

Solutions:
* Move the FTP client class under the ProcessWire namespace
...or...
* Add use ProcessWire\DUP_Logs and ProcessWire\Duplicator and so on...

**Comment by flydev-fr** [comment] 2022-03-23 14:57
thanks again, if you need an update asap send a PR, or I will check it on evening

**Comment by Alpine418** [comment] 2022-03-23 15:05
Did a PR. Please check and test...

**Comment by flydev-fr** [comment] 2022-03-23 15:29
it's merged on the dev branch - you can update it from this last version (1.4.21) by the time.

**Closed as completed** 2022-03-23 18:38 UTC
